In [1]:
import pandas as pd
import numpy as np
from datetime import datetime

In [2]:
pd.set_option("display.max_columns", None)

In [3]:
# registro = pd.read_excel(r'C:\Users\jober\OneDrive\Desktop\BD_CO\BD_Registro_2024_2025_acumulado.xlsx',sheet_name='BD_Acumulado-2024-2025')
registro = pd.read_excel(r'C:\Users\jober\Downloads\BD_Registro_2024_2025_acumulado.xlsx',sheet_name='BD_Acumulado-2024-2025')
# "C:\Users\jober\Downloads\BD_Registro_2024_2025_acumulado.xlsx"

c:\Users\jober\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:85: UserWarning: Data Validation extension is not supported and will be removed
  for idx, row in parser.parse():

In [4]:
registro.columns

Index(['No. ', 'Programa / Aliado\n(Si aplica)', 'Barrio donde vive',
       'Tipo Documento', 'Número Documento', 'TIPO_REGISTRO', 'Nombres',
       'Apellidos', 'Celular', 'Teléfono', 'Canal de Registro', 'Edad',
       'Rango_Edad', 'Género', 'Nivel de Estudio', 'Título Homologado',
       'Ciudad de Residencia', 'Email', 'Fecha Registro',
       'Programa de Gobierno', 'Condiciones Especiales',
       'Detalle Discapacidades', 'Situación Laboral', 'Agente Registra',
       'Fecha Actualización', '% Hoja Vida', 'Prestador Anterior',
       'Fecha Cambio Prestador', 'Vereda/Localidad/Centro Poblado',
       'Pertenece A', 'SISE_OFFLINE', 'Mes', 'Año', 'Punto Atención'],
      dtype='object')

In [5]:
registro.head()

,No.,Programa / Aliado\n(Si aplica),Barrio donde vive,Tipo Documento,Número Documento,TIPO_REGISTRO,Nombres,Apellidos,Celular,Teléfono,Canal de Registro,Edad,Rango_Edad,Género,Nivel de Estudio,Título Homologado,Ciudad de Residencia,Email,Fecha Registro,Programa de Gobierno,Condiciones Especiales,Detalle Discapacidades,Situación Laboral,Agente Registra,Fecha Actualización,% Hoja Vida,Prestador Anterior,Fecha Cambio Prestador,Vereda/Localidad/Centro Poblado,Pertenece A,SISE_OFFLINE,Mes,Año,Punto Atención
0,1,NaN,NaN,Cédula de Ciudadanía,1043665968,Registro_nuevo,DAYANA CECILIA,PÉREZ SUÁREZ,-,3235338963,Autoregistro,21.0,18 - 28,F,Técnica Laboral,técnico profesional en seguridad y salud en el...,BARRANQUILLA,dayanaperez1003@gmail.com,01/01/2024 12:36:05 p. m.,NaN,NaN,NaN,NO REGISTRA,Autoregistro,01/01/2024 12:36:05 p. m.,INCOMPLETA,NaN,NaN,NaN,NaN,NaN,1,2024,Barrios San José
1,2,NaN,NaN,Cédula de Ciudadanía,1079991248,Registro_nuevo,ELBA ESTHER,FUENTES ACUÑA,-,3006398462,Autoregistro,31.0,29 - 39,F,Universitaria,TRABAJADORA SOCIAL,BARRANQUILLA,fuenteselba24@gmail.com,01/01/2024 01:19:31 p. m.,NaN,NaN,NaN,NO REGISTRA,Autoregistro,01/01/2024 01:19:31 p. m.,INCOMPLETA,NaN,NaN,NaN,NaN,NaN,1,2024,Barrios San José
2,3,NaN,NaN,Cédula de Ciudadanía,1043670020,Registro_nuevo,ADRIANYS LUCIA,FERNANDEZ JARABA,-,3107410880,Autoregistro,27.0,18 - 28,F,Universitaria,Psicóloga,BARRANQUILLA,anyelis.russo@gmail.com,02/01/2024 07:56:04 a. m.,NaN,NaN,NaN,Empleado,Autoregistro,02/01/2024 07:56:04 a. m.,COMPLETA,NaN,NaN,NaN,Urbano,NaN,1,2024,Barrios San José
3,4,NaN,NaN,Cédula de Ciudadanía,1003361352,Registro_nuevo,LUIS FERNANDO,PEREZ FRANCO,-,3024234712,Autoregistro,28.0,18 - 28,M,NaN,NaN,BARRANQUILLA,luisperezfranco.17@hotmail.com,02/01/2024 08:40:53 a. m.,NaN,NaN,NaN,NO REGISTRA,Autoregistro,02/01/2024 08:40:53 a. m.,INCOMPLETA,NaN,NaN,NaN,NaN,NaN,1,2024,Barrios San José
4,5,NaN,NaN,Cédula de Ciudadanía,45593583,Registro_nuevo,PAOLA MARGARITA,DE CASTRO PALACIO,-,3132255023,Autoregistro,46.0,40 - 49,F,Especialización,GERENCIA TRIBUTARIA,SOLEDAD,contadora78@hotmail.com,02/01/2024 09:30:22 a. m.,NaN,NaN,NaN,Desempleado,Autoregistro,02/01/2024 09:30:22 a. m.,COMPLETA,NaN,NaN,NaN,Urbano,NaN,1,2024,Barrios San José

In [6]:
# Typing column the names 
registro.columns = registro.columns.str.lower()
registro.columns = registro.columns.str.replace(" ","_")

In [7]:
# cleaning the columns
registro['número_documento'] = registro['número_documento'].astype(str).str.strip()
registro['teléfono'] = registro['teléfono'].astype(str).str.strip()
registro['título_homologado'] = registro['título_homologado'].astype(str).str.strip()
registro['ciudad_de_residencia'] = registro['ciudad_de_residencia'].astype(str).str.strip()
registro['email'] = registro['email'].astype(str).str.strip()
registro['programa_de_gobierno'] = registro['programa_de_gobierno'].astype(str).str.strip()
registro['fecha_actualización'] = registro['fecha_actualización'].astype(str).str.strip()
registro['%_hoja_vida'] = registro['%_hoja_vida'].astype(str).str.strip()
registro['fecha_cambio_prestador'] = registro['fecha_cambio_prestador'].astype(str).str.strip()
registro['vereda/localidad/centro_poblado'] = registro['vereda/localidad/centro_poblado'].astype(str).str.strip()
registro['celular'] = registro['celular'].astype(str).str.strip()

In [8]:
# Registros sin tipo de documento
non_td = registro[registro['tipo_documento'].isnull()].index
# Registro sin número de documento
non_nd = registro[registro['número_documento'].isnull()].index

In [9]:
# All the elements with out information
to_revisit = pd.Series(list(set(non_td).union(set(non_nd))))
wrong = registro[registro.index.isin(to_revisit)]

# Those need to be sent into an excel document
# current date
date = datetime.now().strftime("%Y-%m-%d")
# wrong.to_excel(f"revisar-{date}.xlsx", index=False)

In [10]:
# The valid results are:
valid = registro[~registro.index.isin(to_revisit)]
valid = valid[valid['año']==2025]
valid.shape

(6857, 34)

In [11]:
valid.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6857 entries, 7824 to 14836
Data columns (total 34 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   no._                             6857 non-null   int64
 1   programa_/_aliado
(si_aplica)    3980 non-null   object
 2   barrio_donde_vive                1982 non-null   object
 3   tipo_documento                   6857 non-null   object
 4   número_documento                 6857 non-null   object
 5   tipo_registro                    6857 non-null   object
 6   nombres                          6856 non-null   object
 7   apellidos                        6856 non-null   object
 8   celular                          6857 non-null   object
 9   teléfono                         6857 non-null   object
 10  canal_de_registro                6857 non-null   object
 11  edad                             6842 non-null   float64
 12  rango_edad                       6857 non-null   object
 13  género                           6851 non-null   object
 14  nivel_de_estudio                 5440 non-null   object
 15  título_homologado                6857 non-null   object
 16  ciudad_de_residencia             6857 non-null   object
 17  email                            6857 non-null   object
 18  fecha_registro                   6857 non-null   object
 19  programa_de_gobierno             6857 non-null   object
 20  condiciones_especiales           4698 non-null   object
 21  detalle_discapacidades           193 non-null    object
 22  situación_laboral                6612 non-null   object
 23  agente_registra                  6809 non-null   object
 24  fecha_actualización              6857 non-null   object
 25  %_hoja_vida                      6857 non-null   object
 26  prestador_anterior               242 non-null    object
 27  fecha_cambio_prestador           6857 non-null   object
 28  vereda/localidad/centro_poblado  6857 non-null   object
 29  pertenece_a                      2149 non-null   object
 30  sise_offline                     199 non-null    object
 31  mes                              6857 non-null   int64
 32  año                              6857 non-null   int64
 33  punto_atención                   6857 non-null   object
dtypes: float64(1), int64(3), object(30)
memory usage: 1.8+ MB

In [12]:
# Cleaning NaN data. Data as 'nan' are not actual "NaN":
for column in valid.columns:
    valid[column] = valid[column].replace('nan', pd.NA)

In [13]:
# Clean gender
valid['género'] = valid['género'].replace({'m':'M','f':'F'})

# FECHAS DE REGISTRO

In [14]:
valid['fecha_registro'] = valid['fecha_registro'].fillna("")
valid['fecha_actualización'] = valid['fecha_actualización'].fillna("")

# Function to handle different date formats
def parse_dates(date_str):
    if pd.isna(date_str) or date_str == "":  # Handle empty strings or NaN
        return pd.NaT
    
    date_str = str(date_str).strip()
    
    # Case 1: Excel serial number
    if date_str.isdigit():
        return pd.to_datetime(int(date_str), origin='1899-12-30', unit='D')

    # Case 2: DD-MM-YYYY format
    try:
        return pd.to_datetime(date_str, format="%d-%m-%Y")
    except ValueError:
        pass  # If it fails, try the next method
    
    # Case 3: Other datetime formats
    return pd.to_datetime(date_str, errors='coerce', dayfirst=True)  

# Convert date columns
valid['fecha_registro'] = valid['fecha_registro'].apply(parse_dates)
valid['fecha_actualización'] = valid['fecha_actualización'].apply(parse_dates)

# Get the latest date
valid['fecha_accion'] = valid[['fecha_registro', 'fecha_actualización']].max(axis=1)

# Floor the date to remove time (ensures it's still a datetime object)
valid['fecha_accion'] = valid['fecha_accion'].dt.floor('D')

# # Convert to string format for final output
# valid['fecha_registro'] = valid['fecha_registro'].dt.strftime('%Y-%m-%d')
# valid['fecha_actualización'] = valid['fecha_actualización'].dt.strftime('%Y-%m-%d')
# valid['fecha_accion'] = valid['fecha_accion'].dt.strftime('%Y-%m-%d')

# valid.drop(['fecha_reg','fecha_act'],axis=1, inplace=True)

C:\Users\jober\AppData\Local\Temp\ipykernel_15816\3744391535.py:22: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce', dayfirst=True)

# PREPARING FOR POPULATION ANALYSIS

In [15]:
valid['condiciones_especiales'].unique()

array([nan, 'Ninguna de las anteriores, Ningún grupo étnico',
       'Visual, Ningún grupo étnico', 'Ninguna de las anteriores',
       'Ninguna de las anteriores, Ningún grupo étnico, Ninguna de las anteriores, Ningún grupo étnico',
       'Auditiva, Ningún grupo étnico',
       'Ninguna de las anteriores, Ninguna de las anteriores',
       'Personas en procesos de reintegración, Visual, Palenquero de San Basilio de Palenque, Vendedores informales',
       'Ningún grupo étnico, Psicosocial (mental)',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Auditiva',
       'Indígenas, Trastorno mental, Múltiple, Vendedores informales',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Ninguna de las anteriores',
       'Indígenas, Vendedores informales, Ninguna de las anteriores',
       'Auditiva, Ningún grupo étnico, Auditiva, Ningún grupo étnico',
       'Vendedores informales, Ninguna de las anteriores, Ningún grupo étnico',
       'Visual, Vendedores informales, Ningún grupo étnico',
       'Psicosocial (mental)', 'Auditiva',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Personas en procesos de reintegración, Ninguna de las anteriores',
       'Ningún grupo étnico',
       'Ningún grupo étnico, Ninguna de las anteriores',
       'Indígenas, Estuvo bajo medida de protección del Instituto Colombiano de Bienestar Familiar, Ninguna de las anteriores',
       'Vendedores informales, Ningún grupo étnico',
       'Estuvo bajo medida de protección del Instituto Colombiano de Bienestar Familiar, Ninguna de las anteriores, Ningún grupo étnico',
       'Física  ', 'Indígenas, Ninguna de las anteriores',
       'Ninguna de las anteriores, Vendedores informales, Ningún grupo étnico',
       'Palenquero de San Basilio de Palenque, Ninguna de las anteriores',
       'Cognitiva o Intelectual, Ningún grupo étnico',
       'Física  , Ningún grupo étnico',
       'Retornado, Ninguna de las anteriores, Ningún grupo étnico',
       'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina, Ninguna de las anteriores',
       'Gitano(a) o Rrom, Ninguna de las anteriores',
       'Personas en procesos de reintegración, Ninguna de las anteriores, Ningún grupo étnico',
       'VISUAL', 'FÍSICA', 'AUDITIVA', 'Física',
       'NARP (Negro, Afrocolombiano, Raizal o Palenquero)', 'MÚLTIPLE',
       'Retornado o migrante', 'MULTIPLE', 'Psicosocial', 'Múltiple',
       'PSICOSOCIAL', 'MCH', 'Visual', 'Sordoceguera', 'Cognitivo',
       'MCH ',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Ninguna de las anteriores, Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Ninguna de las anteriores',
       'Auditiva, Auditiva',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Afrocolombianos, Ninguna de las anteriores, Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Afrocolombianos, Ninguna de las anteriores, Afrocolombianos',
       'Indígenas',
       'Ninguna de las anteriores, Negro(a), mulato(a), afrodescendiente, afrocolombiano(a)',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Vendedores informales, Ninguna de las anteriores',
       'Ningún grupo étnico, Ninguna de las anteriores, Vendedores informales',
       'Auditiva, Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina',
       'Palenquero de San Basilio de Palenque',
       'Indígenas, Retornado o migrante', 'Física, Retornado o migrante',
       'Personas en procesos de reintegración, Ningún grupo étnico, Ninguna de las anteriores',
       'Cognitiva o Intelectual',
       'Física  , Vendedores informales, Ningún grupo étnico',
       'Indígenas, Visual',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Visual',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a)',
       'NINGUNA', 'DISCAPACIDAD', 'DISCAPACIDAD INTELECTUAL',
       'JUVENTUDES',
       'NINGUNA, Negro(a), mulato(a), afrodescendiente, afrocolombiano(a)',
       'NINGUNO', 'NINGUNA, INDIGENAS', 'DISCAPACIDAD ',
       'DISCAPACIDAD FISICA', 'INTELECTUAL, PSICOSOCIAL, MÚLTIPLE ',
       'MIGRANTE', 'VCA', 'discapacidad fisica', 'DISCAPACIDAD AUDITIVA',
       'CHATLEMOS', 'DISCAPACIDAD VISUAL (BAJA VISION)',
       'DISCAPACIDAD FÍSICA', 'DISCAPACIDAD COGNITIVA',
       'SENA MULTILINGUIMO', 'SENA MULTILINGUISMO', 'DISCAPACIDAD VISUAL',
       'MUJER CABEZA DE HOGAR', 'REMITIDA DE OFICINA DE LA MUJER',
       'DISCAPCIDAD MULTIPLE SORDO', 'COGNITOIVA', 'FISICA', 'mch',
       'REMITIDA OFICINA DE LA MUJER', 'ACTUALIZAZIO DE  AUTOREGISTRO',
       'REMITIDA OFICINA DE LA MUJER(ITALO LEGUIA)',
       'OFICINA DE LA MUJER (ÍTALO LEGUÍA)', 'AUTOREGISTRO (MARZO 2025)',
       'ACTUALIZACION', 'ACTUALIZACIÓN', 'DISCAPACIDAD AUDITIVA ',
       'DISCAPCIDAD AUDITIVA', 'discapacida cognitiva',
       'MIGRACIÓN COLOMBIA (JORNADA ESPECIAL 7,8,9-04-2025)',
       'HIJO DE VCA', 'NINGINA', 'VENDEDORES AMBULANTES', 'REINTEGRACIÓN',
       'GRUPO ETNICO', 'dISCAPACIDAD FÍSICA', 'COGNITIVA',
       'LIMITADA AUDITIVA',
       'Vendedores informales, Ninguna de las anteriores, Ningún grupo étnico, Vendedores informales, Ninguna de las anteriores, Ningún grupo étnico, Ninguna de las anteriores',
       'Vendedores informales, Ningún grupo étnico, Psicosocial (mental)',
       'Ninguna de las anteriores, Ninguna de las anteriores, Ningún grupo étnico, Ningún grupo étnico',
       'Indígenas, Ninguna de las anteriores, Indígenas, Ninguna de las anteriores',
       'Múltiple, Ningún grupo étnico',
       'Vendedores informales, Ninguna de las anteriores',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Personas en procesos de reintegración, Psicosocial (mental)',
       'NINGUNA ', 'AUTOREGISTRO MARZO 2025',
       'PRSONA CON DISCAPACIDAD AUDITIVA',
       'PERSONA CON DISCAPACIDAD VISUAL', 'AUDITIVA- FISICA',
       'DISCAPACIDAD MULTIPLE', 'ninguna',
       'PERSONA CON DISCAPACIDAD AUDITIVA',
       'VISUAL- PERDIDA PARCIAL DE LA VISION OJO IZQUIERDO- SIN CERTIFICADO',
       'DISCAPACIDAD PSICOSOCIAL ', 'PERSONA CON LIMITACION AUDITIVA',
       'JOVENES', 'PERSONA CON LIMITACION EN SU MANO IZQUIERDA',
       'RETORNADO', 'DISCAPACIDAD FISICA ',
       'PERSONA CON DISCPACIDAD AUDITIVA',
       'PERSONA CON DISCAPACIDAD PSICOSOCIAL', 'NNGUNO',
       'PERSONA CON DISCAPACIDAD AUDITIVVA',
       'PERSONACON DISCPACIDAD AUDITIVA', 'SECRETARÍA PRIVADA ',
       'EXT-QUILLA-2025-0079804', 'EXT-QUILLA-2025-0079878',
       'EXT-QUILLA-2025-0084732', 'EXT-QUILLA-2025-0082249',
       'AUTOREGISTRO', 'EXT-QUILLA-2025-0084321',
       'EXT-QUILLA-2025-0086073', 'EXT-QUILLA-2025-0070585',
       'EXT-QUILLA-2025-0083353', 'JUVENTUDES/VCA',
       'EXT-QUILLA-2025-0072089', 'JUVENTUDES/MIGRANTE',
       'JUVENTUDES/DISCAPACIDAD', 'EXT-QUILLA-2025-0073059',
       'EXT-QUILLA-25-052469', 'EXT-QUILLA-25-055683',
       'EXT-QUILLA-25-058970', 'EXT-QUILLA-25-055026',
       'EXT-QUILLA-25-063786', 'VCA/ATENCIÓN CRAV',
       'EXT-QUILLA-25-064714', 'JUVENTUDES/VCA/ATENCIÓN CRAV',
       'EXT-QUILLA-25-065295', 'ATENCIÓN CRAV', 'MIGRANTE/ATENCIÓN CRAV',
       'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina, Ninguna de las anteriores, Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina, Ninguna de las anteriores',
       'Retornado, Ninguna de las anteriores',
       'Raizal del Archipiélago de San Andrés, Providencia y Santa Catalina',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Retornado, Ninguna de las anteriores',
       'Personas en procesos de reintegración, Visual, Ningún grupo étnico',
       'Discapacidad', 'VCA/JUVENTUDES', 'NNGUNA', 'Ninguna',
       'FERIA FUPAD', 'LINEA 195 (6054010205)',
       'PERSONA CON DISCAPACIDAD FISICA', 'INDIGENAS', 'NINGUNOI',
       'AFROCOLOMBIANO', 'COGNITIVA-INTELECTUAL',
       'PERSONA CON DISCAPACIADAD AUDITIVA', 'ICBF', 'NINGUAN',
       'PERSONA DISCAPACIDAD FISICA', 'PERSONA CON DISCAPACIDAD MULTIPLE',
       'PALADAR HENDIDO', 'PERSONA CON DISCPACIDAD FISICA',
       'PERSONA CON DISCPACIDAD VISUAL ',
       'PERSONACON DISCAPACIDAD COGNITIVA',
       'Personas en procesos de reintegración, Ninguna de las anteriores, Personas en procesos de reintegración, Ninguna de las anteriores',
       'Gitano(a) o Rrom, Vendedores informales, Psicosocial (mental)',
       'Negro(a), mulato(a), afrodescendiente, afrocolombiano(a), Estuvo bajo medida de protección del Instituto Colombiano de Bienestar Familiar, Ninguna de las anteriores',
       'Palenquero de San Basilio de Palenque, Vendedores informales, Ninguna de las anteriores',
       'PERSONA DISCAPACIDAD VISUAL',
       'PERSONA CON DISCAPACACIDAD AUDITIVA',
       'PERSONA CON DISCAPCIDAD AUDITIVA',
       'PERSONA CON DISCAPACIDAD SORDA', 'ADULTO MAYOR', ' NINGUNA',
       'INDIGENA', 'DISCAPACIDAD PSICOSOCIAL', 'AUTOREGISTRO MAYO 2025',
       'PERSONA ON DISCAPACIADAD AUDITIVA', 'PQRSD', 'RETORNADA',
       'PERSONA COGNITIVA INTELECTUAL',
       'EXT-QUILLA-2025-0094890   18/07/2025', 'PCH',
       'EXT-QUILLA-2025-0089124   18/07/2025',
       'EXT-QUILLA-2025-0088919   18/07/2025',
       'EXT-QUILLA-2025-0093441    18/07/2025',
       'EXT-QUILLA-2025-0089124   21/07/2025',
       'PERSONA CON DISCAPCIDAD FISICA', 'PERSONA DISCAPACIDAD AUDITIVA',
       'EXT-QUILLA-2025-0093363   21-07-2025',
       'PERSONA CON DISCAPCIDAD COGNITIVA',
       'EXT-QUILLA-2025-0087330   22-07-2025', 'PQR', 'AUTORREGISTRO',
       'EXT-QUILLA-2025-0088919    22-07-2025',
       'OFICINA DE LA MUJER (REMITIDA POR, JOSÉ MARÍA PAEZ SANTIAGO)',
       'VCA/PQR', 'EXT-QUILLA-2025-0092086   23-07-2025',
       'JUVENTUDES/AUTOREGISTRO', 'PERSONA CON DISCAPACIDAD  FISICA ',
       'MADRE CUIADADORA DE NIÑO EN CONDICION DE DISCAPACIDAD',
       'PROGRAMA TODERO ', 'AUTOREGISTRO JULIO 2025',
       'FUNDACIÓN PROYECTARSE', 'NINGUNA/AUTOREGISTRO',
       'REMITIDA POR UNIDAD DE VICTIMAS (SEDE JUAN MINA)',
       'REGISTRO PAQUE ALEGRA', 'JUVENTUDES-ALEGRA',
       'PINAR DEL RÍO ISRAAID',
       'DISCAPACIDAD MULTIPLE, INTELECTUAL-PSICOSOCIAL',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (1/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (2/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS ',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (3/15)',
       'PERSONA CON DISCAPACIDA AUDITIVA',
       'FERIA CC PARQUE ALEGRA - HV FISICAS', 'PARQUE ALEGRA',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (4/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (5/15)',
       'FERIA CC PARQUE ALEGRA - H.V SISTEMATIZADAS',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (6/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (7/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (8/15)',
       'FERIA CC PARQUE ALEGRA',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (9/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (10/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (12/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (13/15)',
       'FERIA CC PARQUE ALEGRA - H.V FISICAS (15/15)',
       'FERIA CC PARQUE ALEGRA - H.V ',
       'DISCAPACIDAD - DIFICIL ATENCIÓN ',
       'FERIA CC PARQUE ALEGRA LINK DE ASISTENCIA',
       'PERSONACON DISCAPACIDAD FISICA', 'JUVENTUDES/FERIA PARQUE ALEGRA',
       'FERIA LA LOMA INTEGRATE MAS', 'NINGUNA/FERIA PARQUE ALEGRA',
       'BASE FERIA CC ALEGRA LISTA LUZ AMPARO',
       'JUVENTUDES/BASE FERIA ALEGRA',
       'Afrocolombianos, Ninguna de las anteriores, Ningún grupo étnico',
       'Indígenas, Indígenas', 'Ningún grupo étnico, Ningún grupo étnico',
       'Auditiva, Víctima de violencia, Auditiva, Víctima de violencia',
       'Afrocolombianos, Víctima de violencia, Ninguna de las anteriores, Ningún grupo étnico, Afrocolombianos, Víctima de violencia, Ninguna de las anteriores, Ningún grupo étnico, Afrocolombianos',
       'Ninguna de las anteriores, Ningún grupo étnico, Ninguna de las anteriores, Ningún grupo étnico, Ninguna de las anteriores, Ningún grupo étnico, Ninguna de las anteriores',
       'Indígenas, Estuvo bajo medida de protección del Instituto Colombiano de Bienestar Familiar',
       'Física  , Física  ',
       'Física  , Ningún grupo étnico, Física  , Ningún grupo étnico',
       'Cognitiva o Intelectual, Ningún grupo étnico, Cognitiva o Intelectual, Ningún grupo étnico',
       'Múltiple, Múltiple',
       'Visual, Ningún grupo étnico, Visual, Ningún grupo étnico',
       'FERIA PARQUE ALEGRA', 'NINIGUNA', 'FERIA PARQUE ALEGRA LINK',
       'INTEGRATE+ 28/08/2025 BARRIO LA LOMA', 'juventudez',
       'AUTOREGISTRO JULIO', 'FORMACIÓN', 'NINGUA',
       'DISCAPACIDAD COGNITIVA LEVE',
       'NINGUNA/CONVOCATORIA ASESOR COMERCIAL',
       'AUTOREGISTRO JULIO DE 2025', 'PERSONA CON DISCAPACIDAD MULTIPLA',
       'JEFE DE HOGAR', 'CUIDADORA', 'JUVENTUDES/FERIA PARUQE ALEGRA',
       'AUTOREGISTRO AGOSTO',
       'REMITIDA EDIFICIO CENTRAL (PASEO BÓLIVAR) ATENCIÓN AL CIUDADANO',
       'MIGRANTE/FERIA PARQUE ALEGRA', 'CAPACIDAD AUDITIVA REDUCIDA',
       'JUVENTUDES/AUTORREGISTRO', 'PEWRSONA CON DISCAPACIDAD VISUAL',
       'AUTOREGISTRO AGOSTO 2025', 'NUNGUNA',
       'PERSONA CON DISCAPCIADAD FISICA', 'FORMACION',
       'ARTICULACIÓN CON LA FUNDACIÓN GRUPO ÉXITO', 'MIGRANTE/CATLEMOS',
       'DISCAPACIDAD MÚLTIPLE', 'JUVENTUDES/AUTOREGISTRO AGOSTO 2025',
       'JUVENTUDES/FUNDACIÓN GRUPO ÉXITO', 'AUTOREGISTROS AGOSTO 2025',
       'DICAPACIDAD COGNITIVA (SIN CERTIFICADO)', 'joan',
       'REMITIDO POR LA DRA. GRACE ESTRATEGIA CHATLEMOS',
       'PERSONA CON DISCAPACIDAD COGNITIVA'], dtype=object)

# GRUPOS ETNICOS

In [16]:
# Ensure conditions are strings and lowercase
valid['condiciones_especiales'] = valid['condiciones_especiales'].astype(str).str.lower().fillna('')

# Define filters
filter_afro = valid['condiciones_especiales'].str.contains('negr|afro|mulat|palen', regex=True)
filter_raizal = valid['condiciones_especiales'].str.contains('raiz', regex=True)
filter_indig = valid['condiciones_especiales'].str.contains('indí', regex=True)
filter_git = valid['condiciones_especiales'].str.contains('git', regex=True)

def get_ethnic_groups(row):
    groups = []
    if filter_afro[row.name]: groups.append("Afrodescendiente")
    if filter_raizal[row.name]: groups.append("Raizal y/o Isleño")
    if filter_indig[row.name]: groups.append("Indígenas")
    if filter_git[row.name]: groups.append("Gitano")
    return groups if groups else np.nan  # Use NaN for empty lists

# Apply the function
valid["grupos_etnicos"] = valid.apply(get_ethnic_groups, axis=1)

# VICTIMAS DEL CONFLICTO ARMADO

In [17]:
# Poblacion VCA 
valid['programa_de_gobierno'].astype(str)
valid['programa_de_gobierno'] = valid['programa_de_gobierno'].fillna('')

valid['vca'] = pd.Series(dtype='object') # Adding a new column

filter_vca = (
    (valid['programa_de_gobierno'].str.contains('armado', na=False)) |
    (valid['condiciones_especiales'].str.contains('vca|v.c.a'))
)

valid.loc[filter_vca,'vca'] = 'VCA'

# PERSONAS EN CONDICION DE DISCAPACIDAD

In [18]:
# Initialize the column with NaN directly
valid['discapacidad'] = pd.Series([np.nan] * len(valid), dtype='object')

# Mapping of patterns to labels
discapacidad_patterns = {
    r'ognitiv|telect': 'Cognitiva o Intelectual',
    r'[ií]sic': 'Física',
    r'visual': 'Visual',
    r'auditiva': 'Auditiva',
    r'múltiple': 'Múltiple',
    r'sordoceguera': 'Sordoceguera',
    r'psicosocial': 'Psicosocial',
    r'capacidad': 'Discapacidad'
}

# Apply patterns
for pattern, label in discapacidad_patterns.items():
    mask = valid['condiciones_especiales'].str.contains(pattern, case=False, na=False)
    valid.loc[mask, 'discapacidad'] = label

# MIGRANTES

In [19]:
valid.condiciones_especiales.unique()

array(['nan', 'ninguna de las anteriores, ningún grupo étnico',
       'visual, ningún grupo étnico', 'ninguna de las anteriores',
       'ninguna de las anteriores, ningún grupo étnico, ninguna de las anteriores, ningún grupo étnico',
       'auditiva, ningún grupo étnico',
       'ninguna de las anteriores, ninguna de las anteriores',
       'personas en procesos de reintegración, visual, palenquero de san basilio de palenque, vendedores informales',
       'ningún grupo étnico, psicosocial (mental)',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), auditiva',
       'indígenas, trastorno mental, múltiple, vendedores informales',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), ninguna de las anteriores',
       'indígenas, vendedores informales, ninguna de las anteriores',
       'auditiva, ningún grupo étnico, auditiva, ningún grupo étnico',
       'vendedores informales, ninguna de las anteriores, ningún grupo étnico',
       'visual, vendedores informales, ningún grupo étnico',
       'psicosocial (mental)', 'auditiva',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), personas en procesos de reintegración, ninguna de las anteriores',
       'ningún grupo étnico',
       'ningún grupo étnico, ninguna de las anteriores',
       'indígenas, estuvo bajo medida de protección del instituto colombiano de bienestar familiar, ninguna de las anteriores',
       'vendedores informales, ningún grupo étnico',
       'estuvo bajo medida de protección del instituto colombiano de bienestar familiar, ninguna de las anteriores, ningún grupo étnico',
       'física  ', 'indígenas, ninguna de las anteriores',
       'ninguna de las anteriores, vendedores informales, ningún grupo étnico',
       'palenquero de san basilio de palenque, ninguna de las anteriores',
       'cognitiva o intelectual, ningún grupo étnico',
       'física  , ningún grupo étnico',
       'retornado, ninguna de las anteriores, ningún grupo étnico',
       'raizal del archipiélago de san andrés, providencia y santa catalina, ninguna de las anteriores',
       'gitano(a) o rrom, ninguna de las anteriores',
       'personas en procesos de reintegración, ninguna de las anteriores, ningún grupo étnico',
       'visual', 'física',
       'narp (negro, afrocolombiano, raizal o palenquero)', 'múltiple',
       'retornado o migrante', 'multiple', 'psicosocial', 'mch',
       'sordoceguera', 'cognitivo', 'mch ',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), ninguna de las anteriores, negro(a), mulato(a), afrodescendiente, afrocolombiano(a), ninguna de las anteriores',
       'auditiva, auditiva',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), afrocolombianos, ninguna de las anteriores, negro(a), mulato(a), afrodescendiente, afrocolombiano(a), afrocolombianos, ninguna de las anteriores, afrocolombianos',
       'indígenas',
       'ninguna de las anteriores, negro(a), mulato(a), afrodescendiente, afrocolombiano(a)',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), vendedores informales, ninguna de las anteriores',
       'ningún grupo étnico, ninguna de las anteriores, vendedores informales',
       'auditiva, raizal del archipiélago de san andrés, providencia y santa catalina',
       'palenquero de san basilio de palenque',
       'indígenas, retornado o migrante', 'física, retornado o migrante',
       'personas en procesos de reintegración, ningún grupo étnico, ninguna de las anteriores',
       'cognitiva o intelectual',
       'física  , vendedores informales, ningún grupo étnico',
       'indígenas, visual',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), visual',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a)',
       'ninguna', 'discapacidad', 'discapacidad intelectual',
       'juventudes',
       'ninguna, negro(a), mulato(a), afrodescendiente, afrocolombiano(a)',
       'ninguno', 'ninguna, indigenas', 'discapacidad ',
       'discapacidad fisica', 'intelectual, psicosocial, múltiple ',
       'migrante', 'vca', 'discapacidad auditiva', 'chatlemos',
       'discapacidad visual (baja vision)', 'discapacidad física',
       'discapacidad cognitiva', 'sena multilinguimo',
       'sena multilinguismo', 'discapacidad visual',
       'mujer cabeza de hogar', 'remitida de oficina de la mujer',
       'discapcidad multiple sordo', 'cognitoiva', 'fisica',
       'remitida oficina de la mujer', 'actualizazio de  autoregistro',
       'remitida oficina de la mujer(italo leguia)',
       'oficina de la mujer (ítalo leguía)', 'autoregistro (marzo 2025)',
       'actualizacion', 'actualización', 'discapacidad auditiva ',
       'discapcidad auditiva', 'discapacida cognitiva',
       'migración colombia (jornada especial 7,8,9-04-2025)',
       'hijo de vca', 'ningina', 'vendedores ambulantes', 'reintegración',
       'grupo etnico', 'cognitiva', 'limitada auditiva',
       'vendedores informales, ninguna de las anteriores, ningún grupo étnico, vendedores informales, ninguna de las anteriores, ningún grupo étnico, ninguna de las anteriores',
       'vendedores informales, ningún grupo étnico, psicosocial (mental)',
       'ninguna de las anteriores, ninguna de las anteriores, ningún grupo étnico, ningún grupo étnico',
       'indígenas, ninguna de las anteriores, indígenas, ninguna de las anteriores',
       'múltiple, ningún grupo étnico',
       'vendedores informales, ninguna de las anteriores',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), personas en procesos de reintegración, psicosocial (mental)',
       'ninguna ', 'autoregistro marzo 2025',
       'prsona con discapacidad auditiva',
       'persona con discapacidad visual', 'auditiva- fisica',
       'discapacidad multiple', 'persona con discapacidad auditiva',
       'visual- perdida parcial de la vision ojo izquierdo- sin certificado',
       'discapacidad psicosocial ', 'persona con limitacion auditiva',
       'jovenes', 'persona con limitacion en su mano izquierda',
       'retornado', 'discapacidad fisica ',
       'persona con discpacidad auditiva',
       'persona con discapacidad psicosocial', 'nnguno',
       'persona con discapacidad auditivva',
       'personacon discpacidad auditiva', 'secretaría privada ',
       'ext-quilla-2025-0079804', 'ext-quilla-2025-0079878',
       'ext-quilla-2025-0084732', 'ext-quilla-2025-0082249',
       'autoregistro', 'ext-quilla-2025-0084321',
       'ext-quilla-2025-0086073', 'ext-quilla-2025-0070585',
       'ext-quilla-2025-0083353', 'juventudes/vca',
       'ext-quilla-2025-0072089', 'juventudes/migrante',
       'juventudes/discapacidad', 'ext-quilla-2025-0073059',
       'ext-quilla-25-052469', 'ext-quilla-25-055683',
       'ext-quilla-25-058970', 'ext-quilla-25-055026',
       'ext-quilla-25-063786', 'vca/atención crav',
       'ext-quilla-25-064714', 'juventudes/vca/atención crav',
       'ext-quilla-25-065295', 'atención crav', 'migrante/atención crav',
       'raizal del archipiélago de san andrés, providencia y santa catalina, ninguna de las anteriores, raizal del archipiélago de san andrés, providencia y santa catalina, ninguna de las anteriores',
       'retornado, ninguna de las anteriores',
       'raizal del archipiélago de san andrés, providencia y santa catalina',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), retornado, ninguna de las anteriores',
       'personas en procesos de reintegración, visual, ningún grupo étnico',
       'vca/juventudes', 'nnguna', 'feria fupad',
       'linea 195 (6054010205)', 'persona con discapacidad fisica',
       'indigenas', 'ningunoi', 'afrocolombiano', 'cognitiva-intelectual',
       'persona con discapaciadad auditiva', 'icbf', 'ninguan',
       'persona discapacidad fisica', 'persona con discapacidad multiple',
       'paladar hendido', 'persona con discpacidad fisica',
       'persona con discpacidad visual ',
       'personacon discapacidad cognitiva',
       'personas en procesos de reintegración, ninguna de las anteriores, personas en procesos de reintegración, ninguna de las anteriores',
       'gitano(a) o rrom, vendedores informales, psicosocial (mental)',
       'negro(a), mulato(a), afrodescendiente, afrocolombiano(a), estuvo bajo medida de protección del instituto colombiano de bienestar familiar, ninguna de las anteriores',
       'palenquero de san basilio de palenque, vendedores informales, ninguna de las anteriores',
       'persona discapacidad visual',
       'persona con discapacacidad auditiva',
       'persona con discapcidad auditiva',
       'persona con discapacidad sorda', 'adulto mayor', ' ninguna',
       'indigena', 'discapacidad psicosocial', 'autoregistro mayo 2025',
       'persona on discapaciadad auditiva', 'pqrsd', 'retornada',
       'persona cognitiva intelectual',
       'ext-quilla-2025-0094890   18/07/2025', 'pch',
       'ext-quilla-2025-0089124   18/07/2025',
       'ext-quilla-2025-0088919   18/07/2025',
       'ext-quilla-2025-0093441    18/07/2025',
       'ext-quilla-2025-0089124   21/07/2025',
       'persona con discapcidad fisica', 'persona discapacidad auditiva',
       'ext-quilla-2025-0093363   21-07-2025',
       'persona con discapcidad cognitiva',
       'ext-quilla-2025-0087330   22-07-2025', 'pqr', 'autorregistro',
       'ext-quilla-2025-0088919    22-07-2025',
       'oficina de la mujer (remitida por, josé maría paez santiago)',
       'vca/pqr', 'ext-quilla-2025-0092086   23-07-2025',
       'juventudes/autoregistro', 'persona con discapacidad  fisica ',
       'madre cuiadadora de niño en condicion de discapacidad',
       'programa todero ', 'autoregistro julio 2025',
       'fundación proyectarse', 'ninguna/autoregistro',
       'remitida por unidad de victimas (sede juan mina)',
       'registro paque alegra', 'juventudes-alegra',
       'pinar del río israaid',
       'discapacidad multiple, intelectual-psicosocial',
       'feria cc parque alegra - h.v fisicas (1/15)',
       'feria cc parque alegra - h.v fisicas (2/15)',
       'feria cc parque alegra - h.v fisicas ',
       'feria cc parque alegra - h.v fisicas (3/15)',
       'persona con discapacida auditiva',
       'feria cc parque alegra - hv fisicas', 'parque alegra',
       'feria cc parque alegra - h.v fisicas (4/15)',
       'feria cc parque alegra - h.v fisicas (5/15)',
       'feria cc parque alegra - h.v sistematizadas',
       'feria cc parque alegra - h.v fisicas (6/15)',
       'feria cc parque alegra - h.v fisicas (7/15)',
       'feria cc parque alegra - h.v fisicas (8/15)',
       'feria cc parque alegra',
       'feria cc parque alegra - h.v fisicas (9/15)',
       'feria cc parque alegra - h.v fisicas (10/15)',
       'feria cc parque alegra - h.v fisicas (12/15)',
       'feria cc parque alegra - h.v fisicas (13/15)',
       'feria cc parque alegra - h.v fisicas (15/15)',
       'feria cc parque alegra - h.v ',
       'discapacidad - dificil atención ',
       'feria cc parque alegra link de asistencia',
       'personacon discapacidad fisica', 'juventudes/feria parque alegra',
       'feria la loma integrate mas', 'ninguna/feria parque alegra',
       'base feria cc alegra lista luz amparo',
       'juventudes/base feria alegra',
       'afrocolombianos, ninguna de las anteriores, ningún grupo étnico',
       'indígenas, indígenas', 'ningún grupo étnico, ningún grupo étnico',
       'auditiva, víctima de violencia, auditiva, víctima de violencia',
       'afrocolombianos, víctima de violencia, ninguna de las anteriores, ningún grupo étnico, afrocolombianos, víctima de violencia, ninguna de las anteriores, ningún grupo étnico, afrocolombianos',
       'ninguna de las anteriores, ningún grupo étnico, ninguna de las anteriores, ningún grupo étnico, ninguna de las anteriores, ningún grupo étnico, ninguna de las anteriores',
       'indígenas, estuvo bajo medida de protección del instituto colombiano de bienestar familiar',
       'física  , física  ',
       'física  , ningún grupo étnico, física  , ningún grupo étnico',
       'cognitiva o intelectual, ningún grupo étnico, cognitiva o intelectual, ningún grupo étnico',
       'múltiple, múltiple',
       'visual, ningún grupo étnico, visual, ningún grupo étnico',
       'feria parque alegra', 'niniguna', 'feria parque alegra link',
       'integrate+ 28/08/2025 barrio la loma', 'juventudez',
       'autoregistro julio', 'formación', 'ningua',
       'discapacidad cognitiva leve',
       'ninguna/convocatoria asesor comercial',
       'autoregistro julio de 2025', 'persona con discapacidad multipla',
       'jefe de hogar', 'cuidadora', 'juventudes/feria paruqe alegra',
       'autoregistro agosto',
       'remitida edificio central (paseo bólivar) atención al ciudadano',
       'migrante/feria parque alegra', 'capacidad auditiva reducida',
       'juventudes/autorregistro', 'pewrsona con discapacidad visual',
       'autoregistro agosto 2025', 'nunguna',
       'persona con discapciadad fisica', 'formacion',
       'articulación con la fundación grupo éxito', 'migrante/catlemos',
       'discapacidad múltiple', 'juventudes/autoregistro agosto 2025',
       'juventudes/fundación grupo éxito', 'autoregistros agosto 2025',
       'dicapacidad cognitiva (sin certificado)', 'joan',
       'remitido por la dra. grace estrategia chatlemos',
       'persona con discapacidad cognitiva'], dtype=object)

In [20]:
# Migrant and internally displaced people
valid['migrante'] = ""

# Filters applied
filter_mig = (
    (valid['condiciones_especiales'].str.contains('migr|retor')) |
    (valid['tipo_documento'].str.contains('acional|ermiso|tranje'))
)

valid.loc[filter_mig,"migrante"] = "Migrante o Retornado"

# Replace empty strings with NaN
valid['migrante'] = valid['migrante'].replace("", np.nan)

In [21]:
valid['tipo_documento'].value_counts()

tipo_documento
Cédula de Ciudadanía                    6438
Documento Nacional de Identificación     279
Tarjeta de Identidad                      81
Permiso de Proteccion Temporal - PPT      58
Cédula de extranjeria                      1
Name: count, dtype: int64

# VÍCTIMA DE VIOLENCIA

In [22]:
# Population VVG
valid['vvg'] = ""

# Filters applied
filter_vvg = (
    (valid['condiciones_especiales'].str.contains('viole')) |
    (valid['condiciones_especiales'].str.contains('vvg'))     
)

valid.loc[filter_vvg,"vvg"] = "vvg"

# Replace empty strings with NaN
valid['vvg'] = valid['vvg'].replace("",  np.nan)

# REINSERTADOS

In [23]:
# Reincorporados
valid['reincorporados'] = ""

# Filters applied
filter_rei = (
    (valid['condiciones_especiales'].str.contains('rein'))
)

valid.loc[filter_rei,"reincorporados"] = "reincorporados"

# Replace empty strings with NaN
valid['reincorporados'] = valid['reincorporados'].replace("", np.nan)

In [24]:
print(valid['%_hoja_vida'].apply(type).unique())

[<class 'pandas._libs.missing.NAType'> <class 'str'>]

## Exporting the data to parquet

In [25]:
# valid.to_csv("registrados_2025.csv", index=False)
# valid.to_parquet("registrados_2024.parquet", engine="pyarrow", index=False)

In [26]:
# The new registries for this months are
today = datetime.today()

if today.month == 1:
    prev_month = 12
    prev_year = today.year - 1
else:
    prev_month = today.month - 1
    prev_year = today.year

In [27]:
# Hojas de Vida autoregistro
fr_autoregistro = (pd.to_datetime(valid['fecha_accion']).dt.month == prev_month) & (valid['canal_de_registro'] == 'Autoregistro') & (valid['tipo_registro'] == 'Registro_nuevo') & (pd.to_datetime(valid['fecha_accion']).dt.year == prev_year)

print(f'El número de HV de hombres autoregistradas durante el mes {prev_month} es: {valid[fr_autoregistro & (valid['género']=='M')]['género'].count()}')
print(f'El número de HV de mujeres autoregistradas durante el mes {prev_month} es: {valid[fr_autoregistro & (valid['género']=='F')]['género'].count()}')
print()

print(f'El número de HV autoregistradas para PCD durante el mes {prev_month} es: {valid[fr_autoregistro & (valid['discapacidad'])]['discapacidad'].count()}')
print(f'El número de HV autoregistradas para VCA durante el mes {prev_month} es: {valid[fr_autoregistro]['vca'].count()}')
print(f'El número de HV autoregistradas para VVG durante el mes {prev_month} es: {valid[fr_autoregistro]['vvg'].count()}')
print(f'El número de HV autoregistradas para migrantes durante el mes {prev_month} es: {valid[fr_autoregistro]['migrante'].count()}')
print(f'El número de HV autoregistradas para grupos étnicos durante el mes {prev_month} es: {valid[fr_autoregistro]['grupos_etnicos'].count()}')
print(f'El número de HV autoregistradas para personas en reincorporacion durante el mes {prev_month} es: {valid[fr_autoregistro]['reincorporados'].count()}')
print()

print(f'El número de HV con autoregistro nuevo para adultos mayores durante el mes {prev_month} es: {valid[fr_autoregistro & (valid['edad'] >= 60)]['género'].count()}')
print(f'El número de HV con autoregistro nuevo para adultos durante el mes {prev_month} es: {valid[fr_autoregistro & (valid['edad'] >= 29) & (valid['edad'] < 60)]['género'].count()}')
print(f'El número de HV con autoregistro nuevo para jovenes durante el mes {prev_month} es: {valid[fr_autoregistro & (valid['edad'] <= 28)]['género'].count()}')

El número de HV de hombres autoregistradas durante el mes 9 es: 131
El número de HV de mujeres autoregistradas durante el mes 9 es: 226

El número de HV autoregistradas para PCD durante el mes 9 es: 13
El número de HV autoregistradas para VCA durante el mes 9 es: 24
El número de HV autoregistradas para VVG durante el mes 9 es: 0
El número de HV autoregistradas para migrantes durante el mes 9 es: 5
El número de HV autoregistradas para grupos étnicos durante el mes 9 es: 21
El número de HV autoregistradas para personas en reincorporacion durante el mes 9 es: 4

El número de HV con autoregistro nuevo para adultos mayores durante el mes 9 es: 8
El número de HV con autoregistro nuevo para adultos durante el mes 9 es: 141
El número de HV con autoregistro nuevo para jovenes durante el mes 9 es: 208

In [28]:
# Hojas de Vida de registros nuevos
fr_nuevo = (pd.to_datetime(valid['fecha_accion']).dt.month == prev_month) & (valid['canal_de_registro'] == 'Agencia') & (valid['tipo_registro'] == 'Registro_nuevo') & (pd.to_datetime(valid['fecha_accion']).dt.year == prev_year)

print(f'El número de HV de hombres con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo & (valid['género']=='M')]['género'].count()}')
print(f'El número de HV de mujeres con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo & (valid['género']=='F')]['género'].count()}')
print()

print(f'El número de HV para PCD con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo & (valid['discapacidad'])]['discapacidad'].count()}')
print(f'El número de HV para victimas con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo]['vca'].count()}')
print(f'El número de HV para Víctimas de Violencia con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo]['vvg'].count()}')
print(f'El número de HV para migrantes con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo]['migrante'].count()}')
print(f'El número de HV para grupos étnicos con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo]['grupos_etnicos'].count()}')
print(f'El número de HV para personas en reincorporacion con registro nuevo durante el mes {prev_month} es: {valid[fr_nuevo]['reincorporados'].count()}')
print()

print(f'El número de HV con registro nuevo para adultos mayores durante el mes {prev_month} es: {valid[fr_nuevo & (valid['edad'] >= 60)]['género'].count()}')
print(f'El número de HV con registro nuevo para adultos durante el mes {prev_month} es: {valid[fr_nuevo & (valid['edad'] >= 29) & (valid['edad'] < 60)]['género'].count()}')
print(f'El número de HV con registro nuevo para jovenes durante el mes {prev_month} es: {valid[fr_nuevo & (valid['edad'] <= 28)]['género'].count()}')

El número de HV de hombres con registro nuevo durante el mes 9 es: 35
El número de HV de mujeres con registro nuevo durante el mes 9 es: 81

El número de HV para PCD con registro nuevo durante el mes 9 es: 3
El número de HV para victimas con registro nuevo durante el mes 9 es: 9
El número de HV para Víctimas de Violencia con registro nuevo durante el mes 9 es: 0
El número de HV para migrantes con registro nuevo durante el mes 9 es: 14
El número de HV para grupos étnicos con registro nuevo durante el mes 9 es: 3
El número de HV para personas en reincorporacion con registro nuevo durante el mes 9 es: 0

El número de HV con registro nuevo para adultos mayores durante el mes 9 es: 7
El número de HV con registro nuevo para adultos durante el mes 9 es: 48
El número de HV con registro nuevo para jovenes durante el mes 9 es: 61

In [29]:
# Hojas de Vida actualizadas
fr_actualizado = (pd.to_datetime(valid['fecha_accion']).dt.month == prev_month) & (valid['canal_de_registro'] == 'Agencia') & (valid['tipo_registro'] == 'Actualizacion') & (pd.to_datetime(valid['fecha_accion']).dt.year == prev_year)

print(f'El número de HV de hombres actualizadas durante el mes {prev_month} es: {valid[fr_actualizado & (valid['género']=='M')]['género'].count()}')
print(f'El número de HV de mujeres actualizadas durante el mes {prev_month} es: {valid[fr_actualizado & (valid['género']=='F')]['género'].count()}')
print()

print(f'El número de HV actualizadas para PCD durante el mes {prev_month} es: {valid[fr_actualizado & (valid['discapacidad'])]['discapacidad'].count()}')
print(f'El número de HV actualizadas para VCA durante el mes {prev_month} es: {valid[fr_actualizado]['vca'].count()}')
print(f'El número de HV actualizadas para VVG durante el mes {prev_month} es: {valid[fr_actualizado]['vvg'].count()}')
print(f'El número de HV actualizadas para migrantes durante el mes {prev_month} es: {valid[fr_actualizado]['migrante'].count()}')
print(f'El número de HV actualizadas para grupos étnicos durante el mes {prev_month} es: {valid[fr_actualizado]['grupos_etnicos'].count()}')
print(f'El número de HV actualizadas para personas en reincorporacion durante el mes {prev_month} es: {valid[fr_actualizado]['reincorporados'].count()}')
print()

print(f'El número de HV actualizadas para adultos mayores durante el mes {prev_month} es: {valid[fr_actualizado & (valid['edad'] >= 60)]['género'].count()}')
print(f'El número de HV actualizadas para adultos durante el mes {prev_month} es: {valid[fr_actualizado & (valid['edad'] >= 29) & (valid['edad'] < 60)]['género'].count()}')
print(f'El número de HV actualizadas para jovenes durante el mes {prev_month} es: {valid[fr_actualizado & (valid['edad'] <= 28)]['género'].count()}')

El número de HV de hombres actualizadas durante el mes 9 es: 63
El número de HV de mujeres actualizadas durante el mes 9 es: 111

El número de HV actualizadas para PCD durante el mes 9 es: 15
El número de HV actualizadas para VCA durante el mes 9 es: 5
El número de HV actualizadas para VVG durante el mes 9 es: 0
El número de HV actualizadas para migrantes durante el mes 9 es: 9
El número de HV actualizadas para grupos étnicos durante el mes 9 es: 0
El número de HV actualizadas para personas en reincorporacion durante el mes 9 es: 0

El número de HV actualizadas para adultos mayores durante el mes 9 es: 5
El número de HV actualizadas para adultos durante el mes 9 es: 103
El número de HV actualizadas para jovenes durante el mes 9 es: 65

In [30]:
# Registros PcD atendidos en el CO 
mes = 9
año = 2025
fm_pcd = (pd.to_datetime(valid['fecha_accion']).dt.month == mes) & (valid['canal_de_registro'] == 'Agencia') & (pd.to_datetime(valid['fecha_accion']).dt.year == año) & (~valid['discapacidad'].isna())

pcd_registries = pd.pivot_table(valid[fm_pcd], values='número_documento' , index='rango_edad', columns='género', aggfunc='count', fill_value=0)
pcd_registries

género      F  M
rango_edad
18 - 28     2  3
29 - 39     5  3
40 - 49     1  2
50 - 59     0  2

In [31]:
# Pro funcionario para el período
# mes = [2, 3, 4]
# año = 2025
# agente = 'bcarreno@barranquilla.gov.co'
# valid = valid[valid['agente_registra'] == agente]

# table = pd.pivot_table(valid, values='número_documento' , index='tipo_registro', columns='mes', aggfunc='count')
# table

In [32]:
# Exporting the data
# prev_year = 2024
# valid = valid[(pd.to_datetime(valid['año']) == prev_year)]
valid = valid[(pd.to_datetime(valid['fecha_accion']).dt.month == prev_month) & (pd.to_datetime(valid['fecha_accion']).dt.year == prev_year)]
# valid.to_parquet(f'registro_hv_2024.parquet', compression='zstd')
valid.to_parquet(f'registro_hv_{prev_year}_{prev_month}.parquet', compression='zstd')

In [33]:
# valid['discapacidad'].value_counts()
# valid.head()
# table = pd.pivot_table(valid, values='número_documento' , index='tipo_registro', columns='mes', aggfunc='count')
# table